services:
  app:
    container_name: invest-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRESQL_URL: ${POSTGRESQL_URL:-postgresql:5432/invest}
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME:-postgres}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD:-root}
      TINKOFF_KEY: ${TINKOFF_KEY}
      OPENAI_KEY: ${OPENAI_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    restart: on-failure
    networks:
      - app-network

  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD:-root}
      POSTGRES_DB: invest
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge