spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/invest
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  tinkoff:
    key: ${TINKOFF_KEY}
  openai:
    key: ${OPENAI_KEY}
  security:
    jwt:
      secret-key: a89c1f6f36f57fda65f1155a296c1a068b3d70903bfbbe87a324556436403a91
      access-lifetime: 1800000 # 30 minutes
      refresh-lifetime: 2592000000 # a month