global:
  scrape_interval: 15s

scrape_configs:
    - job_name: 'invest-app'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['host.docker.internal:8080']
      metric_relabel_configs:
        - source_labels: [__name__, uri]
          regex: 'http_server_requests_seconds_.+;/actuator.*'
          action: drop
